use agent_devkit::{
    ConfigFieldDescriptor, ConfigFieldType, HostPlatform, ProtocolCompatibility,
    ProviderConfigurationSchema, ProviderDescriptor, ProviderKind, SensitiveFieldDescriptor,
};
use semver::{Version, VersionReq};
use std::collections::BTreeSet;
use url::Url;

pub const FIREBASE_IDENTITY_PROVIDER_ID: &str = "agentweave.identity.firebase";

pub fn firebase_identity_provider_descriptor() -> ProviderDescriptor {
    ProviderDescriptor {
        schema_version: 1,
        package_id: "agentweave-identity-firebase".into(),
        provider_id: FIREBASE_IDENTITY_PROVIDER_ID.into(),
        provider_version: Version::parse(env!("CARGO_PKG_VERSION"))
            .expect("crate version must be valid semver"),
        protocol_compatibility: ProtocolCompatibility {
            requirement: VersionReq::parse(">=0.1.0, <0.2.0")
                .expect("static protocol requirement must be valid"),
        },
        kind: ProviderKind::Identity,
        display_name: "Firebase Email Login".into(),
        description: "Signs users in with Firebase Authentication email and password.".into(),
        documentation_url: Url::parse("https://firebase.google.com/docs/auth/web/password-auth")
            .expect("static documentation URL must be valid"),
        risk_notice: "Firebase web configuration is public, but user passwords and session tokens must remain inside the trusted Host.".into(),
        platforms: BTreeSet::from([
            HostPlatform::Macos,
            HostPlatform::Windows,
            HostPlatform::Linux,
            HostPlatform::Server,
        ]),
        capabilities: BTreeSet::from([
            "email_password".into(),
            "gateway_access_assertion".into(),
            "logout".into(),
            "refresh".into(),
        ]),
        configuration_schema: ProviderConfigurationSchema {
            schema_version: 1,
            migration_version: 1,
            public_fields: vec![
                field("projectId", "Firebase Project ID", "Stable Firebase project identifier."),
                field("firebaseWebKey", "Firebase web key", "Public browser API identifier generated by Firebase."),
                field("webApplicationId", "Firebase Web App ID", "Public identifier for the managed Firebase Web App."),
                ConfigFieldDescriptor {
                    required: false,
                    advanced: true,
                    ..field("authDomain", "Authentication domain", "Optional Firebase authentication domain.")
                },
            ],
            sensitive_fields: Vec::new(),
            cross_field_rules: Vec::new(),
        },
        developer_authorization_schema: Some(ProviderConfigurationSchema {
            schema_version: 1,
            migration_version: 1,
            public_fields: vec![ConfigFieldDescriptor {
                required: false,
                advanced: true,
                ..field(
                    "client-id",
                    "Google OAuth client ID",
                    "Optional Desktop OAuth client override for the developer control plane.",
                )
            }],
            sensitive_fields: vec![SensitiveFieldDescriptor {
                id: "client-secret".into(),
                label: "Google OAuth client secret".into(),
                description: "Optional installed-app client secret kept only on the development machine.".into(),
                required: false,
                purpose: "firebase_developer_authorization".into(),
                rotation_supported: false,
                visible_when: None,
            }],
            cross_field_rules: Vec::new(),
        }),
    }
}

fn field(id: &str, label: &str, description: &str) -> ConfigFieldDescriptor {
    ConfigFieldDescriptor {
        id: id.into(),
        label: label.into(),
        description: description.into(),
        field_type: ConfigFieldType::String,
        required: true,
        default_value: None,
        allowed_values: Vec::new(),
        minimum_length: Some(1),
        maximum_length: Some(2048),
        advanced: false,
        visible_when: None,
    }
}
